// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXlqeJjgdIKFJUcnA7wJeUO8ya2jVHqwA',
    appId: '1:806670108923:web:708a6a4755cc944467085e',
    messagingSenderId: '806670108923',
    projectId: 'my-portfolio-2cb03',
    authDomain: 'my-portfolio-2cb03.firebaseapp.com',
    storageBucket: 'my-portfolio-2cb03.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHvSxtKaodhdyuwOZyUIvRCrkUMwVA9U4',
    appId: '1:806670108923:android:31fea454d88ca37167085e',
    messagingSenderId: '806670108923',
    projectId: 'my-portfolio-2cb03',
    storageBucket: 'my-portfolio-2cb03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl6XPh4nnUGJ8C8wEIFC456kX9vJnK1zg',
    appId: '1:806670108923:ios:a3a23650b578815167085e',
    messagingSenderId: '806670108923',
    projectId: 'my-portfolio-2cb03',
    storageBucket: 'my-portfolio-2cb03.appspot.com',
    iosClientId: '806670108923-ip91p9bh36sihmsb3r2b0qr9k3immqu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
